### ISSUE TITLE
Improve Test-Coverage

### ISSUE THREAD

**Issue by santonelli** [collective/collective.sidebar#13]
**Summary**
As a **collective.sidebar-plugin user** I want the **test coverage to be above 95%** so that I have a better feeling when I integrate it into my **production projects**.

**Acceptance Criteria**
* It's done when there are test coverage reports for the project (already done)
* It's done when there are unit tests for all python classes
* It's done when the test coverage is above 95%
* It's done when the current test coverage is visible in our readme-file (already done, but please check)

**Additional notes**
We should really invest some hours on this!

**Comment by Netroxen** [comment]
I've assigned @sarn0ld as we need to improve the test coverage, also with the history section of the sidebar.
