### ISSUE TITLE
Use Actions to Add Static-Links

### ISSUE THREAD

**Issue by santonelli** [collective/collective.sidebar#22]
**Summary**
As a **website admin** I want to be able to **change links in the sidebar** using actions so I can **change the navigation without editing the template**.

**Acceptance Criteria**
* It's done when you can configure the static links in the sidebar
* It's done when I can remove all static links
* It's done when I can define my own static links with:
  * Title
  * Icon
  * URL

**Additional Notes**
The term "static link" refers to items like "Settings", "Login", ....
Some of these links are hardcoded at the moment. We should make them configurable. One option is to make use of actions for that.

**Comment by sarn0ld** [comment]
We need to discuss where the link configuration should be made.
For a start: Is it configured by the website admin? In a control panel?

**Comment by santonelli** [comment]
In a first iteration I'd create a action category (sidebar) and add useful default actions (basically what we have in the template). Configuration only for admins in the ZMI (Action Tool). We can add UI for this later.

**Comment by Netroxen** [comment]
I have implemented this with the pull-request https://github.com/collective/collective.sidebar/pull/35.
