### ISSUE TITLE
Dynamic Navigation Inside Sidebar

### ISSUE THREAD

**Issue by sarn0ld** [collective/collective.sidebar#27]
**Summary**
As a **website user**, I want to be able to **navigate the website structure inside the sidebar**, to **get a better overview** of the whole website **and** to be able to **navigate the whole website** using the sidebar.

**Acceptance Criteria**
- It's done when a click on a folder's icon opens the folder and shows the folder's content **inside the navigation bar**.
- It's done when the navigation root stays visible, even after opening folders by clicking on their icon.
- It's done when a click on a folder's title opens the item's page **outside the navigation bar**.
- It's done when the sidebar does not close when I click on a folder's icon, but refreshes it's content.
- It's done when the icon for an opened folder is an arrow pointing down, while the icon for a closed folder is an arrow pointing to the folder title, 

**Technical Notes**
We need some kind of ajax function for showing a folder's items inside the navigation bar on click of it's icon. Maybe something similar to #11

**Comment by santonelli** [comment]
We decided to always step into a folderish item and display a link on top of the new layer. Future UI improvements are planned.
