### ISSUE TITLE
Add Collapsible Sections

### ISSUE THREAD

**Issue by santonelli** [collective/collective.sidebar#3]
**Summary**
As a **website user**, I want to be able to **collapse sections** in the sidebar, so that I can **turn off sections I am not interested in**.

**Acceptance Criteria**
* It's done when there is a small icon next to each section title which shows/hides the section's content.
* It's done when the icon next to expanded sections is an arrow pointing down.
* It's done when the icon next to a collapsed section is an arrow pointing up.
* It's done when by default all sections are expanded until the user collapses them.
* It's done when there is a setting to generally allow cookies.
* It's done when the default for allow_cookies is disabled.
* It's done when there is a setting to enable collapsible sections.
* It's done when the default for collapsible_sections is disabled.
* It's done when the collapse/expand-state for each section is saved and restored from cookies.

**Comment by Netroxen** [comment]
Should the collapsible sections be persistent between views..? We could store a cookie or something in the browser local-storage to say what sections were collapsed...
