### ISSUE TITLE
Sidebar Positioning

### ISSUE THREAD

**Issue by Netroxen** [collective/collective.sidebar#30]
Story
-------

as a **user**
I want to be able to **configure** how **elements in the sidebar** are displayed
so that I have more **control over the layout**

Acceptance Criteria
--------------------------

- It is done when I can see a tab "Positioning" in the settings panel
- It is done when I can see the following options in the "Positioning" settings
  - Live-Search Position
    - Cover
    - Sidebar
  - Profile Position (TBD)
    - Cover
    - Sidebar
  - Sidebar Position (TBD)
    - Left
    - Right

Technical Notes
---------------------

- For the sidebar position, we also have to create a class or alternative transition for this to work correctly. This class should be applied based on the setting value.

**Comment by sarn0ld** [comment]
We should clearify whether this can coexist with the settings mentioned in #9, or replaces them, or is replaced by them partly...

**Comment by santonelli** [comment]
Fixed with #70.
