### ISSUE TITLE
Navigation Incorrectly Rendered on Page-Not-Found Error

### ISSUE THREAD

**Issue by Netroxen** [collective/collective.sidebar#31]
Summary
------------

in the sidebar **static links section**
for **authenticated users** who visit a **non-existent path**, the **login link is displayed**
and the **navigation links are not visible**

Environment
-----------------

- Plone 5.1.0.1 (5110)
- CMF 2.2.12
- Zope 2.13.26
- Python 2.7.12 (default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
- PIL 4.3.0 (Pillow)

Steps to reproduce
-------------------------

Visit a page that does not exist, enter any URL path to test this.

Expected result
---------------------

The navigation should not display the "Login" link when the user is already authenticated

Current result
------------------

Currently the navigation does not respect if the user is logged in and does not display any links when a page / path that does not exist is navigated to.

Technical Notes
---------------------

- We have to check if the user is authenticated, and if visiting a page that does not exist, we should display the default portal root links.

Diese Sektion ist für technische Hinweise gedacht, falls der Ticketersteller bereits eine Ahnung hat, in welcher Komponente/Klasse der Software sich der Fehler befindet oder wie dieser behoben werden kann.

Screenshots
-----------------

![snap_2018_12_05](https://user-images.githubusercontent.com/7691449/49502782-1fe91b00-f876-11e8-80ed-0c99e873d650.png)
![snap_2018_12_05_1](https://user-images.githubusercontent.com/7691449/49502788-24adcf00-f876-11e8-9195-37502381196e.png)

**Comment by santonelli** [comment]
This is Plone's default behavior and has to do with some security related issues (as far as i remember).
