### ISSUE TITLE
Create a Setting to Disable Cookie Features

### ISSUE THREAD

**Issue by sarn0ld** [collective/collective.sidebar#32]
**Summary** 
As a **website admin**,  I want to have a control panel **option to disable cookie features**, so that I **have control over** whether my website uses **cookies or not**.

**Acceptance Criteria**
* It's done when there is a sidebar control panel.
* It's done when there is an option in the sidebar control panel to "Enable Cookie Features" with Description: "The features Sidebar-Locking and Collapsable-Sections are using cookies. If you don't want to use cookies on your website, you can disable these features here."
* It's done when the default for "Enable Cookie Features" is on/true.
* It's done when the option is respected and it
  * enables/disables Sidebar-Locking #4
  * enables/disables Collapsable-Sections #3

**Comment by santonelli** [comment]
Sidebar locking is not yet merged. Setting is available since collapsible sections.
