### ISSUE TITLE
Select Default View in Sidebar

### ISSUE THREAD

**Issue by Netroxen** [collective/collective.sidebar#33]
Story
-------

as as **user**
I want to be able to **select the default view** of a page
so that I can **change the layout** of the page on-the-fly

Acceptance Criteria
--------------------------

* It's done when I can see a "Default View" link in the sidebar
* It's done when I'm redirected to the selection screen upon clicking "Default View"
* It's done when I see the relevant translation localized in my language
* It's done when the option is visible under the "Display" section

**Comment by sarn0ld** [comment]
I think we should add the link under "Display" not create a new section "Layout". Then it is more consistent to the old toolbar.

**Comment by sarn0ld** [comment]
Caution: As discussed in Wasserburg I only added a link to the "view select_default_view" for this issue. I added another ticket for listing the registered views: #49
