### ISSUE TITLE
List Selectable Views under "Display"

### ISSUE THREAD

**Issue by sarn0ld** [collective/collective.sidebar#49]
This follows #33 

Story
-------

as as **editor**
I want to be able to **select the default view** of a page
so that I can **change the layout** of the page without leaving it.

Acceptance Criteria
--------------------------

* It's done when I can see the list of registred views for a context inside in the sidebar.
* It's done when the list is added in the "Display" section.
* It's done when on click on a list item the view is set as default view for the page. (selectViewTemplate)

**Comment by santonelli** [comment]
This functionality is available by linking to select_default_view opened in a modal. Overlay is fixed in 1.3.0.
