### ISSUE TITLE
Add User Profile-Section to Sidebar

### ISSUE THREAD

**Issue by santonelli** [collective/collective.sidebar#5]
**Summary**
As a **website user** I want to **see my login information**, so that I **know that I am logged in and** get a **warm feeling of being known and welcomed** by the website.

**Acceptance Criteria**
* It's done when there is a new user profile section on top of the sidebar (position TBD?)
* It's done when the section shows this information:
  * User Profile Picture
  * Username (Plone Fullname)
* It's done when the section is not shown to unauthenticated users
* It's done when a click on the section opens the profile settings (@@personal-information)

**Comment by sarn0ld** [comment]
TBD: Where should this section be positioned?

**Comment by santonelli** [comment]
Merged.
