### ISSUE TITLE
Remove main_template Override

### ISSUE THREAD

**Issue by Netroxen** [collective/collective.sidebar#52]
User Story
========

As a developer,
I want to remove any template overrides,
so I can better implement custom theming overrides in my package.

Acceptance Criteria
===============

* It's done when the main_template.pt override has been removed from the package.

**Comment by Netroxen** [comment]
Ideally, the main_template override is nice to have, however it makes overriding the file difficult in packages that depend on collective.sidebar.

For now we remove this to make the usability a little easier.

**Comment by santonelli** [comment]
Please test with other project.

**Comment by sarn0ld** [comment]
I tested on two projects. Didn't have any issues.

See #53
