### ISSUE TITLE
Repair Github/Travis Build for Xenial

### ISSUE THREAD

**Issue by sarn0ld** [collective/collective.sidebar#57]
Some travis machines where updated to Ubuntu 16.04 Xenial which breaks how we start robot tests. 

See https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-services-xvfb

We hotfixed the builds by restricting the machines to Ubuntu 14.04 with #55 .
Now we need a more durable fix for the future.

**Comment by santonelli** [comment]
Updated .travis.yml to use bionic.
