### ISSUE TITLE
Refactor utils.py - crop()

### ISSUE THREAD

**Issue by sarn0ld** [collective/collective.sidebar#65]
While writing tests i found some strange behaviour in the crop()-function in utils.py. Not sure what was intended for this to do exactly. However this needs refactoring. See test_crop() for further information!

**Comment by Netroxen** [comment]
The method is supposed to crop text using word boundaries, not actual character limits. So if a word exceeds the character limit then the method will remove the word and replace it with `...`.

This just looks a little cleaner than abruptly cropping the sentence mid-word. We can add a boolean param that allows text to be cropped on an actual character limit though...

**Comment by sarn0ld** [comment]
Thank you for the information!
Then I wouldn't add the cropping on actual char limit, but do these fixes, so that my test_crop method is green:

- Before iterating to search for the last word inside the limit: Replace the special chars with white spaces
- If the first word is longer than the limit -> Crop after the char-limit instead of just returning "..."

**Comment by sarn0ld** [comment]
I opened a PR as suggestion
