### ISSUE TITLE
Add workflow options to sidebar

### ISSUE THREAD

**Issue by santonelli** [collective/collective.sidebar#7]
We have to add all workflow related options to the sidebar. Every feature that's in Plone's toolbar needs to be added in.

**Comment by Netroxen** [comment]
Please see the pull-request I made https://github.com/collective/collective.sidebar/pull/16.

**Comment by santonelli** [comment]
We did some analysis and Stefan and me refactored a little. Color story needs some improvements. Rest is borrowed from toolbar.
